# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Linux
      run: >
        sudo apt-get update -q &&
        sudo apt-get install --no-install-recommends --quiet --yes
        libpoco-dev
        libeigen3-dev
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Lint with PyLint
      run: |
        mkdir ./pylint
        pylint --rcfile .pylintrc --output-format=text src/ | tee ./pylint/pylint.log || pylint-exit $?
        PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
        anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
        echo "Pylint score is $PYLINT_SCORE"
    - name: Upload PyLint badge
      uses: actions/upload-artifact@v2
      with:
        name: pylint-badge
        path: pylint/pylint.svg
    - name: Test with pytest
      run: |
        pytest --cov=adnap --cov-report xml:coverage.xml
        coverage report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
