# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Linux
      run: >
        apt-get update -q &&
        apt-get install --no-install-recommends --quiet --yes
        libpoco-dev
        libeigen3-dev
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Lint with PyLint
      run: |
        pylint --rcfile .pylintrc src/
    - name: Test with pytest
      run: |
        pytest --cov=adnap --cov-report xml:coverage.xml
        coverage report
    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
